name: mocki
port: 3000
references:
  - type: collection
    id: recipient-with-accounts-empty
    data: {recipients: []}
  - type: collection
    id: recipient-with-accounts
    data: {recipients: [
      {
        recipientId: "1",
        senderId: "2",
        recipientType: "PERSON",
        firstName: "Test",
        lastName: "One",
        fields: [
          {
            id: "LAST_NAME",
            name: "Last name",
            type: "TEXT",
            value: "One"
          },
          {
            id: "FIRST_NAME",
            name: "First name",
            type: "TEXT",
            value: "Test"
          },
          {
            id: "PHONE_NUMBER",
            name: "Mobile phone number",
            type: "PHONE_NUMBER",
            value: {
              number: "8884444444",
              countryIso3Code: "BRL",
              countryPhoneCode: 55
            }
          },
          {
            id: "ADDRESS_COUNTRY",
            name: "Country",
            type: "DROPDOWN",
            value: "BRL"
          },
        ],
        recipientAccounts: [
          {
            dstCurrencyIso3Code: "MXN",
            dstCountryIso3Code: "MEX",
            transferMethod: "BANK_ACCOUNT",
            recipientAccountId: "1",
            accountNumber: "278593857484883616",
            fields: [
              {
                id: "BANK",
                name: "Bank Name",
                type: "DROPDOWN",
                value: "ME50"
              },
              {
                id: "BANK_NAME",
                name: "Bank Name",
                type: "TEXT",
                value: "BANCA MIFEL SA"
              },
              {
                id: "BANK_ACCOUNT_NUMBER",
                name: "Clabe",
                type: "TEXT",
                value: "278593857484883616"
              },
            ]
          }
        ]
      }
    ]}
endpoints:
  - path: /hello
    method: get
    responses:
      - statusCode: 200
        body:
          message: Hello from Mocki!
  - path: /recipients-with-accounts
    metodh: get
    behavior: conditional
    response:
      - statusCode: 200
        condition:
          operator: eq
          comparand: headers.empty
          value: true
        headers:
          - name: content-type
            value: application/json
        body:
          $ref:
            type: collection
            id: recipient-with-accounts-empty
      - statusCode: 200
        condition:
          operator: eq
          comparand: headers.empty
          value: true
        headers:
          - name: content-type
            value: application/json
        body:
          $ref:
            type: collection
            id: recipient-with-accounts


